M48
; DRILL file {KiCad (6.0.11)} date Thu Aug 31 15:14:41 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-31T15:14:41+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.200
%
G90
G05
T1
X-2.0Y-8.6
X0.0Y-8.8
X2.0Y-8.6
T2
X-10.55Y0.3G85X-10.55Y-0.3
G05
X10.55Y0.3G85X10.55Y-0.3
G05
T0
M30
